### ISSUE TITLE
/api/devdata should combine all dev data into 1 response

### ISSUE THREAD

**Issue by keefmoon** [deedubbleyoo/aimia_iOS_data_api#3]
A call to /api/devdata should collect the relevant sub data types, combine them, and provide it as one response. This would reduce the number of calls a client would need to do.
eg.
```
{
    leadtime: 
    {
        value: "14.42"
    },
    "throughput":
    {
        "value":"1.33"
    },
    "forecast":
    {
        "value":"3 Jul 15"
    }
}
```

**Comment by deedubbleyoo** [comment]
I had a go at this last night, but ran into some problems testing it, as I have to stub each of my internal methods, and I've not created the controller in a way that easily supports that.
Also, are you happy having an array of objects (which is still valid JSON)?
